import type { Metadata } from "next";
import { Amaranth } from "next/font/google";
import "./globals.css";

const amaranth = Amaranth({
  variable: "--font-amaranth",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white min-h-screen">
      <body
        className={`${amaranth.variable} antialiased min-h-screen bg-white`}
      >
        <div className="w-full min-h-screen bg-white">
          {children}
        </div>
      </body>
    </html>
  );
}
