services:
  - type: web
    name: subly-email-service
    env: python
    pythonVersion: "3.11"
    rootDir: backend/python-email-service
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM_NAME
        value: Subbie
      - key: EMAIL_FROM_ADDRESS
        sync: false
      - key: EMAIL_PROVIDER
        value: smtp
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_SERVICE_HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: subly-email-service
          property: port 